/*
* AppSettings
*
* Generated By LaravelConnect for iOS on {{Carbon\Carbon::now()->toDateTimeString()}}
* 
* Server Code Version: {{$appVersion}}
*
*/

@include('ios::partials.imports')


public protocol AppSettings : LaravelSettings {

}

public extension AppSettings {
    
    var apiKeyHeaderName: String { return "{{ config('connect.api.key.header') }}" }

    var coreDataModelName: String { return "{{ config("connect.clients.ios.data_model_name") }}" }

    var apiRootPathSegments: [String]  { return {!!$roothPath!!} }

    var serverVersion: String { return "{!!$appVersion!!}" }

    var appName: String { return "{!!addslashes($appName)!!}" }
}
